name: scale asg
on:
  workflow_call:
  push:
    branches:
      - main 
jobs:
  scale_asg:
    runs-on: codebuild-new-runner-${{ github.run_id }}-${{ github.run_attempt }} 
    steps:
      - name: clone repo
        uses: action/checkout@v3
      - name: trigger api
        run: |
          curl -X POST "https://czlwuqtvf4.execute-api.us-east-2.amazonaws.com/dev" -H "Content-Type: application/json" -d @payload.json
